### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by gautz** [ros-planning/moveit_task_constructor#222]
When running ``rosrun moveit_task_constructor_demo scanning``
My computer name has some ``-``sign, I get following error:
```
terminate called after throwing an instance of 'ros::InvalidNameException'
  what():  Character [-] at element [16] is not valid in Graph Resource Name [get_solution_ComputeNameWith-].  Valid characters are a-z, A-Z, 0-9, / and _.
Aborted (core dumped)
```
I can traceback the regression to some time after commit be270cb57466d456ede2131d6cfaa8257b8428d2

**Comment by JafarAbdi** [comment]
@gautz This's should be fixed in https://github.com/ros-planning/moveit_task_constructor/pull/223

**Comment by gautz** [comment]
thanks for the quick fix, execution works! I am still getting an error that may be unrelated.
``Unregistered type: St3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEdSt4lessIS5_ESaISt4pairIKS5_dEEE``

**Comment by JafarAbdi** [comment]
> thanks for the quick fix, execution works! I am still getting an error that may be unrelated.
> `Unregistered type: St3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEdSt4lessIS5_ESaISt4pairIKS5_dEEE`

This corresponds to the following type `std::map<std::string, double>` are you trying to set a property's value to `std::map` .?

**Comment by gautz** [comment]
yes, in cartesian.cpp on line 106:
``std::map<std::string, double> offsets = { { "panda_joint1", M_PI / 6. }, { "panda_joint3", -M_PI / 6 } };``

**Comment by rhaschke** [comment]
You can safely ignore this warning. It just means that you cannot inspect the value of this property in rviz.
